CREATE DATABASE Redlock;
use Redlock;

CREATE TABLE users(
	ID INT PRIMARY KEY NOT NULL,
	Nama VARCHAR(150) NOT NULL,
	Alamat VARCHAR(150) NOT NULL,
	Jabatan VARCHAR(150) NOT NULL
);

INSERT INTO users VALUES
(001, "KELLI", "PLUIT", "MAHASISWI"),
(003, "CLARESTA", "KEMANGGISAN", "MAHASISSWA");
